### ISSUE TITLE
_TypeError (type 'int' is not a subtype of type 'double')

### ISSUE THREAD

**Issue by empire-tm** [sartajroshan/dotlottieloader-flutter#1]
Good afternoon I encountered a problem loading the animation. The file itself was exported from Lottie Workspace.

<img width="707" alt="Снимок экрана 2024-02-10 в 21 07 42" src="https://github.com/sartajroshan/dotlottieloader-flutter/assets/13998894/5d03a991-0a76-4a9a-9fa8-c87b1699b4d5">

**Comment by empire-tm** [comment]
@sartajroshan To solve this problem, please fix `double speed = 1.0;` to `num speed = 1.0;`. I won't be able to send a Pull Request.

<img width="734" alt="Снимок экрана 2024-02-12 в 22 23 18" src="https://github.com/sartajroshan/dotlottieloader-flutter/assets/13998894/dd2bfe05-86d4-4fb7-868a-9052268690bd">

**Comment by sartajroshan** [comment]
@empire-tm  can you share that dotLottie file?

**Comment by TanishqPokharia** [comment]
I am facing the same issue right now
Lottie.asset() does not solve it either and I am getting this error

![image](https://github.com/sartajroshan/dotlottieloader-flutter/assets/114491890/7f6e2c86-75ef-44a2-9a91-9b2275941510)
